FROM node:22.22.0
WORKDIR /usr/src/app

# Needed for container healthchecks
# For alpine images, uncomment the following line:
# RUN apk add --no-cache wget
RUN apt-get update \
  && apt-get install -y --no-install-recommends curl openssl \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm i

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
