run-db-dev:
	npx prisma dev

# Run this command to generate Prisma Client
# If any changes are made to your schema, you will need to rerun the generate command to keep those types in sync.
prisma-generate:
	npx prisma generate
